version: '3.8'

services:
  nginx1:
      restart: always
      image: nginx:1.21.3-alpine
      depends_on:
        - api
        - cms
      env_file: ./env/nginx.env
      command: sh -c "envsubst '$$APP_SEVER_NAME' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
      volumes:
        - ./nginx.template:/etc/nginx/conf.d/nginx.template
        - ./docker/data/logs/nginx/:/var/log/nginx/
      networks:
        - reverse-proxy
        - backnet
  db:
      image: mariadb:10.3.9
      networks:
        - reverse-proxy
        - backnet
      ports:
        - '3306:3306'
      volumes:
        - taskdb:/var/lib/mysql
      env_file: ./env/db.env
  api:
    build: ./app
    volumes:
      - ./app:/code
    ports:
      - '80'
    depends_on:
      - db
    links:
      - db
    networks:
      - reverse-proxy
      - backnet
    env_file: ./env/api.env
    restart: always
  cms:
    build: ./frontend
    restart: always
    networks:
      - reverse-proxy
      - backnet
    env_file: ./env/cms.env
    ports:
      - '3000'
    command:
      "npm run start"
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  backnet:
    driver: bridge
volumes:
    taskdb:
